### ISSUE TITLE
Bug: can no longer import `sp_matrix_to_sp_tensor`

### ISSUE THREAD

**Issue by lukerm** [danielegrattarola/spektral#272]
Hi Daniele,

The changes you made yesterday seems to have broken some code. In particular, this import stopped working on version 1.0.8.

```
$ pip install "spektral==1.0.8"
$ python
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
>>> from spektral.layers.ops import sp_matrix_to_sp_tensor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'sp_matrix_to_sp_tensor' from 'spektral.layers.ops' (/home/luke/.virtualenvs/newspaper/lib/python3.8/site-packages/spektral/layers/ops/__init__.py)
```

On the hand, the import works on the previous version:

```
$ pip install "spektral==1.0.7"
$ python
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
>>> import spektral
>>> spektral.__version__
'1.0.7'
>>> from spektral.layers.ops import sp_matrix_to_sp_tensor
>>>
```

I tried to see where the problem could be in the last three commits, but it wasn't obvious. Please could you take a look?

Thanks,
Luke

**Comment by danielegrattarola** [comment]
Hi, 

that was a recent change that got pushed to PyPi with the last release. 
The `layer.ops` module now only contains functions from tensor to tensor, so that they can be used in layers. Since `sp_matrix_to_sp_tensor` is a function that converts Scipy matrices to tensors, it has been moved to `spektral.utils.sparse`. 

I have updated the docs, thanks for raising the issue.

Cheers

**Comment by lukerm** [comment]
Hi,

Thanks for geting back to me so fast. Makes total sense!

Please consider using the semantic versioning convention in future? I don't think users of your package would expect backward compatibility issues on the bugfix digit! 

Thanks again for the excellent module though.

Luke

**Comment by danielegrattarola** [comment]
You are completely right, I rushed the bugfix and that change slipped through. 

Glad you like the package! 

Cheers
Daniele
